# kubernetes/backstage-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: idp
type: Opaque
data:
  GITHUB_TOKEN: Z2l0aHViX3BhdF8xMUFCSlNaQVkwZ1JDMExsZ2tLZ09NXzA3RFZSV2VRSEprTVJUOWpxaFdxYlBLMEZERDAxMnVwZ29yWmFqUWRJV2hXM0MyWTJXTEtrY1EyY3VE 
