apiVersion: v1
kind: Service
metadata:
  name: backstage-np
  labels:
    app: backstage
    name: backstage-np
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: backstage
  ports:
    - port: 80
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: http
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 
